services:
  postgres_db:
    image: postgres
    restart: always
    container_name: study
    environment:
      - POSTGRES_USER=heather
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=study
    ports:
      - 5432:5432